Repository lunarway/release-manager-bot, pull requests merged in 2023-11, with the labels that each got.

#109 Update golang Docker tag to v1.21.4
  Dockerfile
  Dockerfile-goreleaser
Labels: dependencies

#110 Add template functions
  template.go
Labels: minor

#112 remove replacements
  .goreleaser.yml
Labels: patch

#113 Fix template validation
  main.go
Labels: patch
